// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxrcvowwztaxobuihygj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4cmN2b3d3enRheG9idWloeWdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NjI0MjEsImV4cCI6MjA3MzIzODQyMX0.l_PmLNc2N-ILRN6aA1vrPQWZgvGxJnJFcos2Mjuw-zk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});